name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Check flake
      run: nix flake check --all-systems --show-trace

    - name: Build Darwin configuration
      run: nix build .#darwinConfigurations.gen740.system --show-trace

    - name: Build NixOS T2Mac configuration  
      run: nix build .#nixosConfigurations.nixos-t2mac.config.system.build.toplevel --show-trace

    - name: Build NixOS OrbStack configuration
      run: nix build .#nixosConfigurations.nixos-orbstack.config.system.build.toplevel --show-trace

  format:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Check formatting
      run: |
        nix fmt
        git diff --exit-code
